"""The project's Asset Bundle: the only way goal deliverables reach a workspace, dev included.

<project>/bundle/                       (next to maya.yaml; commit it, your CI/CD deploys it anywhere)
  databricks.yml                        written once; add your own targets here or in CI/CD - MAYA never rewrites it
  resources/maya_variables.yml          one variable per catalog the scripts use (default: the dev name), warehouse_id
  resources/maya_deploy.job.yml         job 'maya_deploy': one task per goal, in goal order
  resources/maya_sync.yml               uploads maya_deploy/ and scripts/ even where .gitignore excludes them
  maya_deploy/run_scripts.py            standalone runner the tasks execute (databricks-sdk only)
  scripts/<goal>/**.sql                 idempotent SQL; catalogs as {{catalog:<dev name>}} tokens
  scripts/<goal>/**.json                declarations of objects SQL cannot create (tags, Genie spaces, dashboards)
  jobs/<goal>/**                        scripts a goal's own scheduled job runs (same runner and tokens)
  resources/maya_<goal>.yml             a goal's own bundle resources (jobs, alerts); catalogs as ${var.catalog_*}
  maya_manifest.json                    which certified run (and approver) produced each goal's scripts

Goal code writes scripts, then deploy() runs `databricks bundle deploy` and `databricks bundle run maya_deploy` for
just that goal's task and files. Nothing a goal delivers is written to the workspace any other way.
"""
import hashlib
import json
import os
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import yaml

from .spec import load_goals

RUNNER = Path(__file__).resolve().parent.parent / "bundle" / "run_scripts.py"
TOKEN = re.compile(r"\{\{catalog:([A-Za-z0-9_\-]+)\}\}")
RESULT = "MAYA_DEPLOY_RESULT "
JOB = "maya_deploy"


class DeployError(RuntimeError):
    pass


class _Dumper(yaml.SafeDumper):
    """Bundle YAML is read by people: repeated values are written out, never as anchors and aliases."""
    def ignore_aliases(self, data):
        return True


def _dump(data) -> str:
    return yaml.dump(data, Dumper=_Dumper, sort_keys=False, width=200)


def settings(system) -> dict:
    return system.spec.get("bundle") or {}


def root(system) -> Path:
    return system.base_dir / settings(system).get("dir", "bundle")


def target(system) -> str:
    return settings(system).get("target", "dev")


def task_key(goal) -> str:
    return f"{goal.id}_{goal.name}"


def _slug(name) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


# ---------------------------------------------------------------- scripts
def tokenize(sql: str, catalogs) -> str:
    """Dev catalog names -> {{catalog:<name>}} wherever they qualify an object (`cat`.x or cat.x)."""
    for cat in sorted(set(catalogs), key=len, reverse=True):
        sql = re.sub(rf"(?<![\w.`{{:])(`?){re.escape(cat)}\1(?=\.)", lambda m: f"{m.group(1)}{{{{catalog:{cat}}}}}{m.group(1)}", sql)
    return sql


def render(title: str, run_id: str, stmts: list[str], catalogs) -> str:
    head = [f"-- MAYA {title}", f"-- generated by run {run_id}; change the goal inputs, not this file", ""]
    body = [f"-- @statement\n{tokenize(s.strip().rstrip(';'), catalogs)};\n" for s in stmts]
    return "\n".join(head) + "\n".join(body)


def scripts_dir(system, goal_id) -> Path:
    return root(system) / "scripts" / goal_id


def jobs_dir(system, goal_id) -> Path:
    return root(system) / "jobs" / goal_id


def resource_file(system, goal_id) -> Path:
    return root(system) / "resources" / f"maya_{goal_id.lower()}.yml"


def script_files(base: Path, any_file=False) -> list[Path]:
    """SQL scripts and JSON declarations (governed tags) of one goal; any_file: every file (a goal's jobs dir also
    holds notebooks, app source and requirements)."""
    if not base.exists():
        return []
    return sorted(p for p in base.rglob("*") if p.is_file() and "__pycache__" not in p.parts
                  and (any_file or p.suffix in (".sql", ".json")))


def _body(text: str) -> str:
    return "\n".join(x for x in text.splitlines() if not x.startswith("-- generated by run "))


def write(ctx, files: dict, catalogs=None, remove=(), jobs=False) -> list[str]:
    """Write a goal's scripts ({relative path: [statements]}, or {path.json: declaration}); returns the paths written
    (relative to the goal dir). A file whose statements are unchanged keeps its content (and generating run).
    jobs=True writes the scripts the goal's own job runs (jobs/<goal>) instead of its deploy scripts; there a str
    value is a file written as is (a notebook, app source, requirements)."""
    base = (jobs_dir if jobs else scripts_dir)(ctx.system, ctx.goal.id)
    cats = set(ctx.system.catalogs) | set(catalogs or ())
    for rel in remove:
        (base / rel).unlink(missing_ok=True)
    out = []
    for rel, stmts in files.items():
        p = base / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(stmts, str):
            text = stmts
        elif rel.endswith(".json"):
            text = tokenize(json.dumps(stmts, indent=1, sort_keys=True), cats) + "\n"
        else:
            text = render(f"{ctx.goal.id} {ctx.goal.title}: {rel}", ctx.run_id, stmts, cats)
        if not p.exists() or _body(p.read_text()) != _body(text):
            p.write_text(text)
        out.append(rel)
    return sorted(out)


def write_resources(ctx, resources: dict | None, catalogs=None) -> Path | None:
    """The goal's own bundle resources ({"jobs": {...}, "alerts": {...}}); dev catalog names become bundle variables
    so every target gets its own catalogs. None removes them."""
    path = resource_file(ctx.system, ctx.goal.id)
    if not resources:
        path.unlink(missing_ok=True)
        return None
    cats = set(ctx.system.catalogs) | set(catalogs or ())
    text = tokenize(_dump({"resources": resources}), cats)
    text = TOKEN.sub(lambda m: f"${{var.catalog_{_slug(m.group(1))}}}", text)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "# maintained by MAYA\n" + text
    if not path.exists() or path.read_text() != body:
        path.write_text(body)
    return path


def _digest(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def undelivered(ctx, rels) -> list[str]:
    """Of the given scripts, those that differ from the goal's last certified delivery (maya_manifest.json)."""
    path = root(ctx.system) / "maya_manifest.json"
    done = (json.loads(path.read_text()) if path.exists() else {}).get("goals", {}).get(ctx.goal.id, {}).get("scripts", {})
    base = scripts_dir(ctx.system, ctx.goal.id)
    return [r for r in rels if done.get(r) != _digest(base / r)]


def _script_catalogs(system) -> list[str]:
    found = set()
    for p in [*(root(system) / "scripts").rglob("*"), *(root(system) / "jobs").rglob("*")]:
        if p.suffix in (".sql", ".json"):
            found |= set(TOKEN.findall(p.read_text()))
    return sorted(found)


# ---------------------------------------------------------------- bundle files
def ensure(system, ws) -> Path:
    r = root(system)
    (r / "resources").mkdir(parents=True, exist_ok=True)
    (r / "maya_deploy").mkdir(exist_ok=True)
    if not (r / "databricks.yml").exists():
        (r / "databricks.yml").write_text(
            "# Asset Bundle of this MAYA project: everything the goals deliver is deployed from here.\n"
            "# MAYA maintains resources/maya_*.yml, maya_deploy/ and scripts/. Add targets for other environments\n"
            "# here or in CI/CD, overriding the variables in resources/maya_variables.yml.\n"
            + yaml.safe_dump({"bundle": {"name": f"maya_{_slug(system.name)}"},
                              "include": ["resources/*.yml"],
                              "targets": {target(system): {"mode": "development", "default": True,
                                                           "workspace": {"host": ws.host}}}}, sort_keys=False))
    cats = _script_catalogs(system)
    variables = {"warehouse_id": {"description": "SQL warehouse that runs the MAYA scripts",
                                  "default": system.spec["target"]["warehouse_id"]}}
    for c in cats:
        variables[f"catalog_{_slug(c)}"] = {"description": f"Catalog that is '{c}' in dev", "default": c}
    _write_yaml(r / "resources" / "maya_variables.yml", {"variables": variables})
    # Bundle sync skips git-ignored files; MAYA's runner and scripts must deploy even where bundle/ is ignored.
    _write_yaml(r / "resources" / "maya_sync.yml", {"sync": {"include": ["../maya_deploy/**", "../scripts/**", "../jobs/**"]}})

    tasks, prev = [], None
    for g in load_goals().values():
        if not scripts_dir(system, g.id).exists():
            continue
        params = ["--scripts", f"${{workspace.file_path}}/scripts/{g.id}", "--warehouse-id", "${var.warehouse_id}"]
        for c in cats:
            params += ["--catalog", f"{c}=${{var.catalog_{_slug(c)}}}"]
        params += ["--only", "{{job.parameters.only}}"]
        t = {"task_key": task_key(g), "environment_key": "maya",
             "spark_python_task": {"python_file": "../maya_deploy/run_scripts.py", "parameters": params}}
        if prev:
            t["depends_on"] = [{"task_key": prev}]
        tasks.append(t)
        prev = task_key(g)
    job = {"name": f"MAYA deploy - {system.name}",
           "parameters": [{"name": "only", "default": ""}],
           "environments": [{"environment_key": "maya", "spec": {"client": "2", "dependencies": ["databricks-sdk>=0.40"]}}],
           "tasks": tasks}
    _write_yaml(r / "resources" / "maya_deploy.job.yml", {"resources": {"jobs": {JOB: job}}})
    dst = r / "maya_deploy" / "run_scripts.py"
    if not dst.exists() or dst.read_bytes() != RUNNER.read_bytes():
        shutil.copyfile(RUNNER, dst)
    return r


def _write_yaml(path, data):
    text = "# maintained by MAYA\n" + _dump(data)
    if not path.exists() or path.read_text() != text:
        path.write_text(text)


# ---------------------------------------------------------------- deploy
def _cli(system, args, cwd):
    cmd = ["databricks", *args]
    prof = system.spec["target"].get("profile")
    if prof:
        cmd += ["-p", prof]
    env = dict(os.environ)
    env.setdefault("DATABRICKS_BUNDLE_ENGINE", settings(system).get("engine", "direct"))  # no Terraform download
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=env)
    return p.returncode, (p.stdout or "") + (p.stderr or "")


def deploy(ctx, files: list[str]) -> dict:
    """Deploy the bundle and run this goal's task for the given scripts (relative to scripts/<goal>)."""
    if not files:
        return {"deployed": [], "note": "no scripts to run"}
    r = ensure(ctx.system, ctx.ws)
    t = target(ctx.system)
    code, out = _cli(ctx.system, ["bundle", "deploy", "-t", t, "--auto-approve"], r)
    if code:
        raise DeployError(f"bundle deploy failed:\n{out[-3000:]}")
    code, out = _cli(ctx.system, ["bundle", "run", JOB, "-t", t, "--only", task_key(ctx.goal),
                                  "--params", f"only={'|'.join(files)}"], r)
    run_id = (re.findall(r"/run/(\d+)", out) or [None])[-1]
    result = _task_result(ctx.ws, run_id, task_key(ctx.goal)) if run_id else {}
    log = {"goal": ctx.goal.id, "files": files, "job_run_id": run_id, "ok": code == 0 and result.get("ok", False),
           "result": result, "at": datetime.now(timezone.utc).isoformat()}
    prev = ctx.read_artefact("deploy.json") or []
    ctx.write_artefact("deploy.json", prev + [log])
    if not log["ok"]:
        raise DeployError(f"deploy job failed for {ctx.goal.id} (run {run_id}): "
                          f"{result.get('failed')} statement {result.get('statement')}: "
                          f"{(result.get('error') or out[-1500:])}")
    ctx.log(f"     deployed via bundle: {len(files)} scripts, {result.get('statements')} statements (job run {run_id})")
    return {"deployed": files, "job_run_id": run_id, "statements": result.get("statements")}


def deploy_resources(ctx) -> None:
    """Deploy the bundle (a goal that delivers only its own resources: jobs, apps, endpoints)."""
    r = ensure(ctx.system, ctx.ws)
    code, out = _cli(ctx.system, ["bundle", "deploy", "-t", target(ctx.system), "--auto-approve"], r)
    if code:
        raise DeployError(f"bundle deploy failed:\n{out[-3000:]}")
    ctx.log("     bundle deployed")


def run_resource(ctx, key: str) -> str:
    """`bundle run` one resource that is not a job (an app: deploys its source and starts it); returns the output."""
    r = ensure(ctx.system, ctx.ws)
    code, out = _cli(ctx.system, ["bundle", "run", key, "-t", target(ctx.system)], r)
    if code:
        raise DeployError(f"bundle run {key} failed:\n{out[-3000:]}")
    ctx.log(f"     ran {key}")
    return out


def run_job(ctx, job_key: str, deploy=True, raise_on_failure=True) -> dict:
    """Run one of the goal's own bundle jobs and wait for it (bundle run blocks until it ends); deploy=True deploys
    the bundle first. raise_on_failure=False returns the result of a failed run (ok False) instead of raising."""
    r = ensure(ctx.system, ctx.ws)
    t = target(ctx.system)
    if deploy:
        code, out = _cli(ctx.system, ["bundle", "deploy", "-t", t, "--auto-approve"], r)
        if code:
            raise DeployError(f"bundle deploy failed:\n{out[-3000:]}")
    code, out = _cli(ctx.system, ["bundle", "run", job_key, "-t", t], r)
    run_id = (re.findall(r"/run/(\d+)", out) or [None])[-1]
    tasks = {}
    if run_id:
        run = ctx.ws.client.jobs.get_run(int(run_id))
        for task in run.tasks or []:
            o = ctx.ws.client.jobs.get_run_output(task.run_id)
            line = next((x for x in reversed((o.logs or "").splitlines()) if x.startswith(RESULT)), None)
            tasks[task.task_key] = json.loads(line[len(RESULT):]) if line else {"ok": False, "error": o.error}
    res = {"job": job_key, "job_run_id": run_id, "ok": code == 0 and all(v.get("ok") for v in tasks.values()),
           "tasks": tasks, "at": datetime.now(timezone.utc).isoformat()}
    if not res["ok"] and (raise_on_failure or not tasks):
        failed = next((v for v in tasks.values() if not v.get("ok")), {})
        raise DeployError(f"job {job_key} failed (run {run_id}): {failed.get('failed')} statement "
                          f"{failed.get('statement')}: {failed.get('error') or out[-1500:]}")
    ctx.log(f"     ran job {job_key} (run {run_id})")
    return res


def summary(system, ws) -> dict:
    """`bundle summary` of the target: its workspace paths and deployed resources."""
    r = ensure(system, ws)
    code, out = _cli(system, ["bundle", "summary", "-t", target(system), "-o", "json"], r)
    if code or "{" not in out:
        return {}
    return json.loads(out[out.index("{"):])


def resources(system, ws) -> dict:
    """The bundle's deployed resources ({kind: {key: {id, name, url, ...}}}) as `bundle summary` reports them."""
    return summary(system, ws).get("resources") or {}


def _task_result(ws, run_id, key) -> dict:
    try:
        run = ws.client.jobs.get_run(int(run_id))
        task = next(t for t in run.tasks if t.task_key == key)
        o = ws.client.jobs.get_run_output(task.run_id)
    except Exception as e:
        return {"ok": False, "error": f"could not read job run output: {e}"}
    for line in reversed((o.logs or "").splitlines()):
        if line.startswith(RESULT):
            return json.loads(line[len(RESULT):])
    return {"ok": False, "error": o.error or (o.logs or "")[-1500:] or "no result from the deploy task"}


def deploy_all(system, ws) -> dict:
    """Deploy the bundle and run every goal's task with all its scripts, as CI/CD does in a fresh environment."""
    r = ensure(system, ws)
    t = target(system)
    code, out = _cli(system, ["bundle", "deploy", "-t", t, "--auto-approve"], r)
    if code:
        raise DeployError(f"bundle deploy failed:\n{out[-3000:]}")
    code, out = _cli(system, ["bundle", "run", JOB, "-t", t], r)
    run_id = (re.findall(r"/run/(\d+)", out) or [None])[-1]
    tasks = {}
    if run_id:
        run = ws.client.jobs.get_run(int(run_id))
        for task in run.tasks or []:
            try:
                o = ws.client.jobs.get_run_output(task.run_id)
                line = next((x for x in reversed((o.logs or "").splitlines()) if x.startswith(RESULT)), None)
                tasks[task.task_key] = json.loads(line[len(RESULT):]) if line else {"ok": False, "error": o.error}
            except Exception as e:
                tasks[task.task_key] = {"ok": False, "error": str(e)}
    return {"ok": code == 0 and all(v.get("ok") for v in tasks.values()), "job_run_id": run_id, "tasks": tasks,
            "output": out[-1500:] if code else None}


def export_all(engine) -> dict:
    """Rebuild every certified goal's scripts from its certified state (goal code: BUNDLE_EXPORT), then the bundle."""
    import importlib
    out = {}
    for g in engine.goals.values():
        hook = getattr(importlib.import_module(f"{g.package}.code"), "BUNDLE_EXPORT", None)
        cert = engine.state.latest_certification(g.id)
        if not hook or not cert or engine.system.self_certified(g.id) is not None:
            continue  # self-certified goals were delivered outside MAYA: nothing to script
        ctx = engine.context(g.id, cert["run_id"])
        module, fn = hook.rsplit(".", 1)
        res = getattr(importlib.import_module(f"{g.package}.code.{module}"), fn)(ctx)
        base = scripts_dir(engine.system, g.id)
        stale = [str(p.relative_to(base)) for p in script_files(base)]
        written = write(ctx, res["files"], catalogs=res.get("catalogs"),
                        remove=[s for s in stale if s not in res["files"]])
        if "jobs" in res:
            jbase = jobs_dir(engine.system, g.id)
            jstale = [str(p.relative_to(jbase)) for p in script_files(jbase, any_file=True)]
            write(ctx, res["jobs"], catalogs=res.get("catalogs"), remove=[s for s in jstale if s not in res["jobs"]], jobs=True)
        if "resources" in res:
            write_resources(ctx, res["resources"], catalogs=res.get("catalogs"))
        record_certification(ctx, cert["certified_by"])
        out[g.id] = written
    ensure(engine.system, engine.ws)
    return out


# ---------------------------------------------------------------- certification
def record_certification(ctx, signed_by) -> Path | None:
    base = scripts_dir(ctx.system, ctx.goal.id)
    jbase, res = jobs_dir(ctx.system, ctx.goal.id), resource_file(ctx.system, ctx.goal.id)
    if not base.exists() and not jbase.exists() and not res.exists():
        return None
    path = root(ctx.system) / "maya_manifest.json"
    m = json.loads(path.read_text()) if path.exists() else {"project": ctx.system.name, "goals": {}}
    from .. import __version__
    m["maya_version"] = __version__
    m["goals"][ctx.goal.id] = {
        "run_id": ctx.run_id, "certified_by": signed_by, "certified_at": datetime.now(timezone.utc).isoformat(),
        "scripts": {str(p.relative_to(base)): _digest(p) for p in script_files(base)}}
    if jbase.exists():
        m["goals"][ctx.goal.id]["jobs"] = {str(p.relative_to(jbase)): _digest(p) for p in script_files(jbase, any_file=True)}
    if res.exists():
        m["goals"][ctx.goal.id]["resources"] = {res.name: _digest(res)}
    path.write_text(json.dumps(m, indent=1, sort_keys=True))
    return path
