"""MAYA operations MCP server (a Databricks App, delivered by G9).

Publishes each approved operation as an MCP tool (streamable HTTP, JSON responses) at /mcp. A tool call starts the
operation's job with typed, validated arguments, waits a bounded time and returns the job's JSON result. Operations
that change data take mode=validate (a dry run) unless the caller asks for mode=run. A call while the operation is
already running returns that run instead of starting another. get_run_status and list_recent_runs report on runs.

Databricks Apps accept OAuth only; the app's service principal holds CAN_MANAGE_RUN on its jobs and nothing else.
operations.json (generated by MAYA from the approved plan) is the whole tool list; job ids come from the app's
resources (environment variables).
"""
import json
import os
import time
from pathlib import Path

from databricks.sdk import WorkspaceClient
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, Response
from starlette.concurrency import run_in_threadpool

SPEC = json.loads((Path(__file__).parent / "operations.json").read_text())
PROTOCOL = "2025-06-18"
MAX_WAIT = int(SPEC.get("max_wait_seconds", 280))
TYPES = {"string": str, "integer": int, "number": (int, float), "boolean": bool}
STATUS_TOOLS = [
    {"name": "get_run_status",
     "description": "Status of an operation run started by one of this server's tools and, once it has finished, the "
                    "operation's JSON result. Use it when a tool returned before its run finished.",
     "inputSchema": {"type": "object", "additionalProperties": False, "required": ["run_id"],
                     "properties": {"run_id": {"type": "integer", "description": "run_id returned by an operation tool"},
                                    "wait_seconds": {"type": "integer", "minimum": 0, "maximum": MAX_WAIT, "default": 0,
                                                     "description": "How long to wait for the run to finish"}}},
     "annotations": {"readOnlyHint": True, "idempotentHint": True}},
    {"name": "list_recent_runs",
     "description": "The most recent runs of one operation (or of all operations): run id, state, start time and who "
                    "started them. Use it to see whether an operation ran, is running or failed.",
     "inputSchema": {"type": "object", "additionalProperties": False,
                     "properties": {"operation": {"type": "string", "enum": ["all"] + [t["name"] for t in SPEC["tools"]],
                                                  "default": "all", "description": "Tool name of the operation, or all"},
                                    "limit": {"type": "integer", "minimum": 1, "maximum": 25, "default": 5,
                                              "description": "Runs per operation"}}},
     "annotations": {"readOnlyHint": True, "idempotentHint": True}},
]

w = WorkspaceClient()
app = FastAPI(title=SPEC["server"])


def _job_id(tool) -> int:
    return int(os.environ[tool["env"]])


def tools() -> list[dict]:
    out = []
    for t in SPEC["tools"]:
        props, required = {}, []
        for p in t["parameters"]:
            s = {"type": p["type"], "description": p["description"]}
            for k in ("enum", "default", "minimum", "maximum"):
                if k in p:
                    s[k] = p[k]
            props[p["name"]] = s
            if "default" not in p:
                required.append(p["name"])
        props["wait_seconds"] = {"type": "integer", "minimum": 0, "maximum": MAX_WAIT, "default": min(120, MAX_WAIT),
                                 "description": "How long to wait for the run to finish before returning its run_id"}
        out.append({"name": t["name"], "description": t["description"],
                    "inputSchema": {"type": "object", "additionalProperties": False, "required": required, "properties": props},
                    "annotations": {"readOnlyHint": not t["writes"], "destructiveHint": False, "idempotentHint": True}})
    return out + STATUS_TOOLS


def _check(schema, args) -> dict:
    props = schema["properties"]
    unknown = sorted(set(args) - set(props))
    if unknown:
        raise ValueError(f"unknown arguments {unknown}")
    out = {}
    for name, s in props.items():
        if name not in args:
            if name in schema.get("required", []):
                raise ValueError(f"missing argument {name}")
            if "default" in s:
                out[name] = s["default"]
            continue
        v = args[name]
        if s["type"] == "integer" and isinstance(v, str) and v.lstrip("-").isdigit():
            v = int(v)
        if not isinstance(v, TYPES[s["type"]]) or (s["type"] != "boolean" and isinstance(v, bool)):
            raise ValueError(f"{name} must be a {s['type']}")
        if "enum" in s and v not in s["enum"]:
            raise ValueError(f"{name} must be one of {s['enum']}")
        if "minimum" in s and v < s["minimum"] or "maximum" in s and v > s["maximum"]:
            raise ValueError(f"{name} must be between {s.get('minimum')} and {s.get('maximum')}")
        out[name] = v
    return out


def _status(run_id, wait_seconds=0) -> dict:
    deadline = time.time() + max(0, min(int(wait_seconds), MAX_WAIT))
    while True:
        run = w.jobs.get_run(run_id)
        state = run.state.life_cycle_state.value if run.state and run.state.life_cycle_state else "UNKNOWN"
        if state in ("TERMINATED", "SKIPPED", "INTERNAL_ERROR") or time.time() >= deadline:
            break
        time.sleep(5)
    out = {"run_id": run_id, "life_cycle_state": state,
           "result_state": run.state.result_state.value if run.state and run.state.result_state else None,
           "run_page_url": run.run_page_url}
    if state == "TERMINATED" and run.tasks:
        o = w.jobs.get_run_output(run.tasks[0].run_id)
        if o.notebook_output and o.notebook_output.result:
            try:
                out["result"] = json.loads(o.notebook_output.result)
            except ValueError:
                out["result"] = o.notebook_output.result
        if o.error:
            out["error"] = o.error
    elif state not in ("TERMINATED", "SKIPPED", "INTERNAL_ERROR"):
        out["note"] = "Still running: call get_run_status with this run_id."
    return out


def call(name, args) -> dict:
    by_name = {t["name"]: t for t in SPEC["tools"]}
    schemas = {t["name"]: t["inputSchema"] for t in tools()}
    if name not in schemas:
        raise ValueError(f"unknown tool {name}")
    a = _check(schemas[name], args or {})
    if name == "get_run_status":
        run = w.jobs.get_run(a["run_id"])
        if run.job_id not in {_job_id(t) for t in SPEC["tools"]}:
            raise ValueError("run_id is not a run of this server's operations")
        return _status(a["run_id"], a.get("wait_seconds", 0))
    if name == "list_recent_runs":
        out = []
        for t in SPEC["tools"]:
            if a.get("operation", "all") in ("all", t["name"]):
                for r in w.jobs.list_runs(job_id=_job_id(t), limit=a.get("limit", 5)):
                    out.append({"operation": t["name"], "run_id": r.run_id, "started": r.start_time,
                                "life_cycle_state": r.state.life_cycle_state.value if r.state and r.state.life_cycle_state else None,
                                "result_state": r.state.result_state.value if r.state and r.state.result_state else None,
                                "started_by": r.creator_user_name})
        return {"runs": out}
    t = by_name[name]
    wait = a.pop("wait_seconds", 0)
    active = next(iter(w.jobs.list_runs(job_id=_job_id(t), active_only=True)), None)
    if active:
        return {"note": "the operation is already running: not started again", **_status(active.run_id, wait)}
    run_id = w.jobs.run_now(job_id=_job_id(t), job_parameters={k: json.dumps(v) if isinstance(v, bool) else str(v)
                                                                for k, v in a.items()}).run_id
    return {"operation": name, "arguments": a, **_status(run_id, wait)}


def _handle(msg):
    method, mid, params = msg.get("method"), msg.get("id"), msg.get("params") or {}
    if mid is None:
        return None
    try:
        if method == "initialize":
            result = {"protocolVersion": params.get("protocolVersion", PROTOCOL), "capabilities": {"tools": {"listChanged": False}},
                      "serverInfo": {"name": SPEC["server"], "version": SPEC["version"]}}
        elif method == "ping":
            result = {}
        elif method == "tools/list":
            result = {"tools": tools()}
        elif method == "tools/call":
            try:
                out = call(params.get("name"), params.get("arguments"))
                result = {"content": [{"type": "text", "text": json.dumps(out, default=str)}],
                          "structuredContent": json.loads(json.dumps(out, default=str)), "isError": False}
            except ValueError as e:
                result = {"content": [{"type": "text", "text": str(e)}], "isError": True}
        else:
            return {"jsonrpc": "2.0", "id": mid, "error": {"code": -32601, "message": f"method {method} not found"}}
        return {"jsonrpc": "2.0", "id": mid, "result": result}
    except Exception as e:
        return {"jsonrpc": "2.0", "id": mid, "error": {"code": -32603, "message": str(e)[:2000]}}


@app.post("/mcp")
async def mcp(request: Request):
    body = await request.json()
    msgs = body if isinstance(body, list) else [body]
    replies = [r for r in [await run_in_threadpool(_handle, m) for m in msgs] if r is not None]
    if not replies:
        return Response(status_code=202)
    return JSONResponse(replies if isinstance(body, list) else replies[0])


@app.get("/mcp")
def mcp_stream():
    return Response(status_code=405)


@app.get("/health")
def health():
    return {"status": "ok", "server": SPEC["server"], "tools": [t["name"] for t in tools()]}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("DATABRICKS_APP_PORT", "8000")))
